---
# Base packages
hardening_base_packages:
  - firewalld
  - policycoreutils-python-utils

# EPEL repository
hardening_epel_rpm: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
hardening_epel_gpg_key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9

# EPEL packages
hardening_epel_packages:
  - fail2ban
  - fail2ban-firewalld

# fail2ban
hardening_fail2ban_jail_path: /etc/fail2ban/jail.d/hardening.conf
